
package view;

import desplazable.Desface;

public class Menucop extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    Desface desplace;
    public Menucop() {
        initComponents();
        desplace = new Desface();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuDezplegable = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JPhome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JPcourse = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        JPestudent = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JPconfi = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHOME = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSlider1 = new javax.swing.JSlider();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelCORSE = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanelESTUDENT = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuDezplegable.setBackground(new java.awt.Color(153, 153, 255));
        MenuDezplegable.setMinimumSize(new java.awt.Dimension(253, 220));
        MenuDezplegable.setPreferredSize(new java.awt.Dimension(253, 220));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");

        JPhome.setBackground(new java.awt.Color(255, 255, 255));
        JPhome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JPhomeMouseMoved(evt);
            }
        });
        JPhome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JPhomeFocusGained(evt);
            }
        });
        JPhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPhomeMouseExited(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HOME");

        javax.swing.GroupLayout JPhomeLayout = new javax.swing.GroupLayout(JPhome);
        JPhome.setLayout(JPhomeLayout);
        JPhomeLayout.setHorizontalGroup(
            JPhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPhomeLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        JPhomeLayout.setVerticalGroup(
            JPhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPhomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPcourse.setBackground(new java.awt.Color(255, 255, 255));
        JPcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPcourseMouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("COURSE");

        javax.swing.GroupLayout JPcourseLayout = new javax.swing.GroupLayout(JPcourse);
        JPcourse.setLayout(JPcourseLayout);
        JPcourseLayout.setHorizontalGroup(
            JPcourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPcourseLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPcourseLayout.setVerticalGroup(
            JPcourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPcourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        JPestudent.setBackground(new java.awt.Color(255, 255, 255));
        JPestudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPestudentMouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ESTUDENT");

        javax.swing.GroupLayout JPestudentLayout = new javax.swing.GroupLayout(JPestudent);
        JPestudent.setLayout(JPestudentLayout);
        JPestudentLayout.setHorizontalGroup(
            JPestudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPestudentLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPestudentLayout.setVerticalGroup(
            JPestudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPestudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPconfi.setBackground(new java.awt.Color(255, 255, 255));
        JPconfi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPconfiMouseClicked(evt);
            }
        });

        jLabel5.setText("CONFIGURACION");

        javax.swing.GroupLayout JPconfiLayout = new javax.swing.GroupLayout(JPconfi);
        JPconfi.setLayout(JPconfiLayout);
        JPconfiLayout.setHorizontalGroup(
            JPconfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPconfiLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPconfiLayout.setVerticalGroup(
            JPconfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPconfiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MenuDezplegableLayout = new javax.swing.GroupLayout(MenuDezplegable);
        MenuDezplegable.setLayout(MenuDezplegableLayout);
        MenuDezplegableLayout.setHorizontalGroup(
            MenuDezplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDezplegableLayout.createSequentialGroup()
                .addGroup(MenuDezplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MenuDezplegableLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPcourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPestudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPconfi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        MenuDezplegableLayout.setVerticalGroup(
            MenuDezplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDezplegableLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addGroup(MenuDezplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuDezplegableLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(JPconfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuDezplegableLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(JPestudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuDezplegableLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(JPcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuDezplegableLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(JPhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(MenuDezplegable, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 240, 570));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 640, -1));

        jPanelHOME.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setText("jRadioButton1");
        jPanelHOME.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 79, -1, -1));

        jScrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jPanelHOME.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));
        jPanelHOME.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jScrollPane1.setViewportView(jEditorPane1);

        jPanelHOME.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));
        jPanelHOME.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 148, -1, -1));
        jPanelHOME.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 191, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BLACK", "FIT", "SMART", "CONVENIO" }));
        jComboBox1.setOpaque(true);
        jPanelHOME.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jPanelHOME.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jScrollPane3.setViewportView(jTree1);

        jPanelHOME.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel1);

        jPanelHOME.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 180, 130));

        jTabbedPane1.addTab("BIENVENIDO", jPanelHOME);

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCORSELayout = new javax.swing.GroupLayout(jPanelCORSE);
        jPanelCORSE.setLayout(jPanelCORSELayout);
        jPanelCORSELayout.setHorizontalGroup(
            jPanelCORSELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCORSELayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanelCORSELayout.setVerticalGroup(
            jPanelCORSELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCORSELayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HOME", jPanelCORSE);

        jPanel5.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ESTUDENT", jPanel2);

        jLabel8.setBackground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("ESTUDENTE");

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelESTUDENTLayout = new javax.swing.GroupLayout(jPanelESTUDENT);
        jPanelESTUDENT.setLayout(jPanelESTUDENTLayout);
        jPanelESTUDENTLayout.setHorizontalGroup(
            jPanelESTUDENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelESTUDENTLayout.createSequentialGroup()
                .addGroup(jPanelESTUDENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelESTUDENTLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel8))
                    .addGroup(jPanelESTUDENTLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanelESTUDENTLayout.setVerticalGroup(
            jPanelESTUDENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelESTUDENTLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("COURSE", jPanelESTUDENT);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 640, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPhomeMouseClicked

        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_JPhomeMouseClicked

    private void JPcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPcourseMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_JPcourseMouseClicked

    private void JPestudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPestudentMouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_JPestudentMouseClicked

    private void JPhomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPhomeMouseMoved
        
    }//GEN-LAST:event_JPhomeMouseMoved

    private void JPhomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JPhomeFocusGained
     
    }//GEN-LAST:event_JPhomeFocusGained

    private void JPhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPhomeMouseEntered
        JPhome.setBackground(new java.awt.Color(173, 216, 230));
    }//GEN-LAST:event_JPhomeMouseEntered

    private void JPhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPhomeMouseExited
        JPhome.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_JPhomeMouseExited

    private void JPconfiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPconfiMouseClicked
        
           int position = this.MenuDezplegable.getX();
        
         if (position >= -1) {
            desplace.desplazarIzquierda(MenuDezplegable, MenuDezplegable.getX(), -170, 10, 10);
        } else if (position>= -170) {
            desplace.desplazarDerecha(MenuDezplegable, MenuDezplegable.getX(), 0, 10, 10);
        }
       
    }//GEN-LAST:event_JPconfiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menucop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menucop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menucop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menucop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menucop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPconfi;
    private javax.swing.JPanel JPcourse;
    private javax.swing.JPanel JPestudent;
    private javax.swing.JPanel JPhome;
    private javax.swing.JPanel MenuDezplegable;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelCORSE;
    private javax.swing.JPanel jPanelESTUDENT;
    private javax.swing.JPanel jPanelHOME;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
